name: PyPI Package Check

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.11'

jobs:
  pypi-check:
    name: Check PyPI package
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install from PyPI
        run: |
          pip install -U pip setuptools wheel
          pip install -U torch --index-url https://download.pytorch.org/whl/cpu
          pip install -U auto_diffusers

      - name: Testing Import
        run: python -c "from auto_diffusers import *"

      - name: HuggingFace test
        run: python -c "from auto_diffusers import EasyPipelineForText2Image; pipe = EasyPipelineForText2Image.from_huggingface('Stable Diffusion')"

      - name: Clean cache
        run: rm -rf ~/.cache/huggingface/hub/* || true

      - name: Civitai test
        continue-on-error: true
        run: python -c "from auto_diffusers import EasyPipelineForText2Image; pipe = EasyPipelineForText2Image.from_civitai('Anything', base_model='SD 1.5')"

